#!/bin/sh
#dxhd &
#xmodmap .config/colemakdhtest &
#xmodmap ~/.config/.Xmodmap &
xset r rate 200 20 &
#volumeicon &
xrdb .config/.Xresources &
nm-applet &
#feh --bg-scale ~/Pictures/wallpaper/158544-download-free-ar-15-wallpaper-1920x1080-image.jpg
#feh --bg-scale ~/Pictures/wallpaper/cat-girl.png &
~/.fehbg
slstatus &
picom &
#xfce4-power-manager &
#/usr/lib/kdeconnectd &
#~/.screenlayout/test1.sh &
/usr/bin/lxpolkit &
#~/.config/polybar/launch.sh &
mpd &
sxhkd &
dunst &

#exec startxfce4
exec dwm

